### PR TITLE
PyPI support

### PR DESCRIPTION
**Pull request by itamarst**
#### ✔ Checklist:

- [x] Commit messages have been written in [Conventional Commits](https://www.conventionalcommits.org) format;
- [x] This PR has been added to [CHANGELOG.md](https://github.com/mgrachev/update-informer/blob/main/CHANGELOG.md) (at the top of the list);
- [x] Tests for the changes have been added (for bug fixes / features).

### CODE REVIEW

**Review by mgrachev — APPROVED** [review]

**Review by mgrachev — COMMENTED** [review]
👋 Thank you for your contribution 🚀

Please fix 2 errors:
```
Compiling update-informer v0.2.0 (/home/runner/work/update-informer/update-informer)
error: environment variable `PYPI_PKG_NAME` not defined
 --> examples/pypi.rs:5:20
  |
5 |     let pkg_name = env!("PYPI_PKG_NAME");
  |                    ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: environment variable `PYPI_PKG_VERSION` not defined
 --> examples/pypi.rs:6:27
  |
6 |     let current_version = env!("PYPI_PKG_VERSION");
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```
https://github.com/mgrachev/update-informer/runs/5052708213?check_suite_focus=true

**Comment by itamarst** [comment]
OK, updated to use different mechanism.

**Comment by mgrachev** [comment]
Another problem:
```
---- src/lib.rs - (line 58) stdout ----
error[E0433]: failed to resolve: use of undeclared type `Duration`
Error:  --> src/lib.rs:61:66
  |
6 | let informer = UpdateInformer::new(PyPI, "yourpackage", "0.1.0", Duration::from_secs(60 * 60 * 24));
  |                                                                  ^^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
3 | use core::time::Duration;
  |
3 | use std::time::Duration;
  |
```
Please add this line `use std::time::Duration;`

**Comment by itamarst** [comment]
Pushed update.

**Review by mgrachev — APPROVED** [review]

**Comment by mgrachev** [comment]
@itamarst Thank you for your help 🔥

**Pull request merged**
